app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, request, redirect, url_for
from flask_login import login_required, current_user
from app.models import User, Concert
import sqlalchemy as sa
from app import db
from app.main import bp


@bp.route('/', methods=['GET'])
def index():
    concert_list = find_latels_concerts(3)
    albums = ['#1', '#2', '#3', '#4']
    return render_template('main/home.html', concert_list=concert_list, albums=albums)


def find_latels_concerts(concert_count=3):
    items = db.session.query(Concert).order_by(
        sa.desc(Concert.date)).limit(concert_count).all()
    concert_list = [
        f"{c.date_str} {c.location[:c.location.find(':')]}" for c in items]
    return concert_list


@bp.route('/bandsite', methods=['GET'])
def show_home_page():
    concert_list = find_latels_concerts()
    albums = ['#1', '#2', '#3', '#4']
    return render_template('main/home.html', concert_list=concert_list, albums=albums)


@bp.route('/bandsite/bandnews', methods=['GET'])
def show_band_news():
    return render_template('main/bandnews.html')


def make_concert_list(page):
    query = sa.select(Concert).order_by(sa.desc(Concert.date))

    concerts = db.paginate(query, page=page, per_page=3, error_out=False)

    next_url = url_for('main.show_concert_list', page=concerts.next_num) \
        if concerts.has_next else None

    prev_url = url_for('main.show_concert_list', page=concerts.prev_num) \
        if concerts.has_prev else None

    ddmm = []
    yy = []
    city = []
    stadium = []

    for elem in concerts.items:
        space_i = elem.date_str.rfind(' ')
        ddmm.append(elem.date_str[:space_i])
        yy.append(elem.date_str[space_i + 1:])

        point_i = elem.location.find(': ')
        city.append(elem.location[:point_i])
        stadium.append(elem.location[point_i + 1:])

    return concerts.items, ddmm, yy, city, stadium, next_url, prev_url


@bp.route('/bandsite/concerts', methods=['GET', 'POST'])
def show_concert_list():
    page = request.args.get('page', 1, type=int)
    items, ddmm, yy, city, stadium, next_url, prev_url = make_concert_list(
        page)
    return render_template('main/concerts.html', concert_list=items, ddmm=ddmm, yy=yy, city=city, stadium=stadium, next_url=next_url, prev_url=prev_url)


@bp.route('/bandsite/music', methods=['GET', 'POST'])
def show_album_list():
    return render_template('main/music.html')


@bp.route('/shop', methods=['GET'])
@login_required
def show_shop_page():
    return render_template('main/shop.html')


@bp.route('/buy_ticket/<concert_id>', methods=['GET', 'POST'])
@login_required
def buy_ticket(concert_id):
    user = db.session.query(User).filter(
        User.username == current_user.username).first()
    if user.concerts_to_visit is None:
        user.concerts_to_visit = str(concert_id)
    elif str(concert_id) not in user.concerts_to_visit:
        user.concerts_to_visit = user.concerts_to_visit + ' ' + str(concert_id)
    db.session.commit()
    return redirect(url_for('auth.user_profile'))

app/templates/main/bandnews.html
{% extends 'base.html' %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='base_style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='nav_style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='homepage.css') }}">
{% endblock %}

{% block conc_img %}
    {{ super() }}
{% endblock %}

{% block main %}
    <h1 style="color: white"> Oops. In progress... </h1>
{% endblock %}

app/templates/main/concerts.html
{% extends 'base.html' %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='base_style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='nav_style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='concertspage.css') }}">
{% endblock %}

{% block conc_img %}
    {{ super() }}
{% endblock %}

{% block main %}
<div class="info_wrapper">
    {% for c in concert_list %}
    <div class="concert_item">
        <div class="date_time">
            <h1> {{ ddmm[loop.index0] }} <br> {{ yy[loop.index0] }} </h1>
        </div>
        <div class="location">
            <h1> {{ city[loop.index0] }} <br> {{ stadium[loop.index0] }} </h1>
        </div>
        <div class="buy_ticket">
            <h1><a href="{{ url_for('main.buy_ticket', concert_id=c.id) }}">Купить билет</a></h1>
        </div>
    </div>
    {% endfor %}
</div>

<table style="width:100%">
    <tr>
      <th>
        {% if prev_url %}
        <!-- <a href="{{ prev_url }}">Newer posts</a> -->
        <form action="{{ prev_url }}" method="post">
            <p>
                <input type="submit" value="newer">
            </p>
        </form>
        {% endif %}
      </th>
      <th>
        {% if next_url %}
        <!-- <a href="{{ next_url }}">Older posts</a> -->
        <form action="{{ next_url }}" method="post">
            <p>
                <input type="submit" value="older">
            </p>
        </form>
        {% endif %}
      </th>
    </tr>
</table>

{% endblock %}

app/templates/main/home.html
{% extends 'base.html' %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='base_style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='nav_style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='homepage.css') }}">
{% endblock %}

{% block nav %}
<header>
    <div id="navbar">
        <ul>
            <li id="main_img"><a href="{{ url_for('main.show_home_page') }}"><img src="{{ url_for('static', filename='/imgs/logo.jpg') }}"></a></li>
            <li><a href="#about">ГРУППА</a></li>
            <li><a href="#concerts">КОНЦЕРТЫ</a></li>
            <li><a href="#music">МУЗЫКА</a></li>
            <li><a href="{{ url_for('main.show_shop_page') }}">МАГАЗИН</a></li>
            {% if current_user.is_anonymous %}
                <li><a href="{{ url_for('auth.login') }}">ВОЙТИ</a></li>
            {% else %}
                <li><a href="{{ url_for('auth.user_profile') }}">ПРОФИЛЬ</a></li>
            {% endif %}
        </ul>
    </div>
</header>
{% endblock %}

{% block conc_img %}
    {{ super() }}
{% endblock %}



{% block main %}
<section id="about">
    <div>
        <h1>О нас</h1>
    </div>
    <div class="info_wrapper">
        <p>История группы история группы история группы история группы история группы 
            история группы история группы история группы история группы история группы 
            история группы история группы история группы история группы история группы 
            история группы история группы история группы история группы история группы ........</p>
    </div>
    <div id="news" class="more_info">
        <a href="{{ url_for('main.show_band_news') }}"><p>Последние новости</p></a>
    </div>
</section>
<section id="concerts">
    <div>
        <h1>Концерты</h1>
    </div>
    <div class="info_wrapper">
        {% for c in concert_list %}
            <div class="concert_item">
                <span>
                    <a href="{{ url_for('main.show_concert_list') }}">
                        <h4> {{ c }} </h4>
                    </a>
                </span>
            </div>
        {% endfor %}
    </div>
    <div id="more_concerts" class="more_info">
        <a href="{{ url_for('main.show_concert_list') }}"><p>Все концерты</p></a>
    </div>
</section>
<section id="music">
    <div><h1>Альбомы</h1></div>
    <div id="album_wrapper" class="info_wrapper">
        <!---Список альбомов (как ссылки)-->
        <ul>
            {% for al in albums %}
                <li><a href="{{ url_for('main.show_album_list') }}">{{al}}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div id="more_music" class="more_info">
        <a href="{{ url_for('main.show_album_list') }}"><p>Все альбомы</p></a>
    </div>
</section>
{% endblock %}

app/templates/main/music.html
{% extends 'base.html' %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='base_style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='nav_style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='musicpage.css') }}">
{% endblock %}

{% block conc_img %}
    {{ super() }}
{% endblock %}

{% block main %}
    <h1 style="color: white"> Oops. In progress... </h1>
{% endblock %}

app/templates/main/shop.html
{% extends 'base.html' %}

{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='base_style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='nav_style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='shoppage.css') }}">
{% endblock %}

{% block conc_img %}
    {{ super() }}
{% endblock %}

{% block main %}
    <h1 style="color: white"> Oops. Shop in progress... </h1>
{% endblock %}